import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {/* Kofi Donations */}
      <Script 
        src='https://storage.ko-fi.com/cdn/scripts/overlay-widget.js' 
        strategy='beforeInteractive' />
        <Script id="kofi-donations" strategy='beforeInteractive'>
        {`kofiWidgetOverlay.draw('tqqq3', {
            'type': 'floating-chat',
            'floating-chat.donateButton.text': 'Tip Me',
            'floating-chat.donateButton.background-color': '#5cb85c',
            'floating-chat.donateButton.text-color': '#fff'
          });`}
        </Script>
    </html>
  );
}
