export type CountryType = 'all' | 'korea' | 'pizza' | 'china' | 'japan' | 'asia' | 'mexico' | 'italy' | 'france';

export const countryLabels: Record<CountryType, string> = {
  all: '아무거나, All',
  korea: '한식, Korea',
  pizza: '피자/치킨/양식',
  china: '중식, China',
  japan: '일식, Japan',
  asia: '아시안, Asia',
  mexico: '스페인, Spain, Mexico',
  italy: '이태리, Italy',
  france: '프랑스, France'
};

type MenuItem = {
  menu: string;
  image: string;
};

export const menus: Record<CountryType, MenuItem[]> = {
  all: [],
  korea: [
    { menu: "김밥 꼬마김밥 충무김밥 참치김밥 유부김밥 불고기김밥 제육김밥 Gimbap", image: "/images/gimbap.jpg" },
    { menu: "라면, 치즈라면, 떡라면, 참치라면, 빨개떡, 콩나물라면, 해장라면, 짬뽕라면 Ramyun", image: "/images/ramyun.jpg" },
    { menu: "떡볶이, 엽기떡볶이 Tteokbbokki, Spicy rice cake", image: "/images/tteokbokki.jpg" },
    { menu: "순대, 찹쌀순대, 오징어순대 Sundae, Blood Sosauge", image: "/images/sundae.jpg" },
    { menu: "족발 Jokbal, pig's trotters", image: "/images/jokbal.jpg" },
    { menu: "어묵탕, 어묵볶음 Eomuk Tang, fish cake soup", image: "/images/eomuk.jpg" },
    { menu: "떡갈비 Tteokgalbi, Grilled Short Rib Patties", image: "/images/ddgb.jpg" },
    { menu: "골뱅이무침 golbaengi-muchim, spicy sea snail salad", image: "/images/golbaengi-muchim.jpg" },
    { menu: "순두부찌개 바지락순두부찌개 sundubujjigae, Soft Bean Curd Stew", image: "/images/sdbjg.jpg" },
    { menu: "아구찜 agu jjim, spicy stewed monkfish", image: "/images/agujjim.jpg" },
    { menu: "부대찌개 BudaeJjigae,  kimchi and hot dog stew", image: "/images/bdjg.webp" },
    { menu: "대게찜 DaegaeJjim, Steamed Snow Crab", image: "/images/dgj.jpg" },
    { menu: "갈비탕 Galbitang, Short Rib Soup", image: "/images/galbitang.jpg" },
    { menu: "감자탕 Gamjatang, pork back-bone stew", image: "/images/gamjatang.jpg" },
    { menu: "낙곱새, 낙지볶음, 낙지덮밥, 낙지소면, 낙지해물찜 nakji bokkeum, spicy stir-fried octopus", image: "/images/ngs.jpg" },
    { menu: "닭볶음탕 Dakbokkeumtang, Spicy Braised Chicken", image: "/images/ddrt.jpg" },
    { menu: "묵은지 돼지김치찜 mugeunji dwaeji kimchi jjim, stewed ribs and aged kimchi ", image: "/images/djkcj.jpg" },
    { menu: "찜닭 안동찜닭 Jjimdak, spicy stewed chicken", image: "/images/jjimdak.jpg" },
    { menu: "해장국 시래기해장국 뼈해장국 Haejang-guk, Hangover soup", image: "/images/bhjg.jpg" },
    { menu: "회 참치회 포항물회 회덮밥 Hoe, Raw fish", image: "/images/hoe.jpg" },
    { menu: "비빔국수, 쫄면, 열무비빔국수, 김치비빔국수, 들기름비빔국수, 코다리비빔국수 Bibim Guksu, Spicy Noodle", image: "/images/bibim.jpg" },
    { menu: "칼국수 들깨칼국수 닭칼국수 매생이굴칼국수 바지락칼국수 얼큰칼국수 쭈꾸미칼국수 Kalguksu, Noodle Soup", image: "/images/kgs.webp" },
    { menu: "수제비, 들깨수제비, 김치수제비 Sujebi, Hand-pulled Dough Soup", image: "/images/sjb.webp" },
    { menu: "물냉면 평양냉면 밀면 Naengmyeon, Cold Noodle", image: "/images/mul-naengmyeon.jpg" },
    { menu: "비빔냉면, 열무냉면, 회냉면, 속초회냉면 Bibim Naengmyeon, Cold Noodle", image: "/images/bibim-naengmyeon.jpg" },
    { menu: "만둣국 Mandu Gook, Dumpling Soup", image: "/images/mandu-guk.jpg" },
    { menu: "육개장, 버섯육개장, 소고기육개장 Yukgaejang, Spicy Beef Soup", image: "/images/ygj.jpg" },
    { menu: "된장찌개 차돌박이된장찌개 된장국 시래기된장국 청국장 doenjangjjigae, Soybean paste soup", image: "/images/djjg.jpg" },
    { menu: "김치찌개 꽁치김치찌개 돼지고기김치찌개 참치김치찌개, kimchijjigae, Kimchi Stew", image: "/images/kcjg.jpg" },
    { menu: "광어매운탕, 꽃게매운탕, 도미매운탕, 쏘가리매운탕 maeuntang, Spicy fish stew", image: "/images/mt.jpg" },
    { menu: "순대국밥 돼지국밥 따로국밥 Sundaegukbap, Blood Sausage and Rice Soup", image: "/images/sundae-gukbap.jpg" },
    { menu: "설렁탕 Seolleongtang, Ox Bone Soup", image: "/images/slt.jpg" },
    { menu: "알밥 Al bap, Fish Roe Rice", image: "/images/al-bap.jpg" },
    { menu: "파전, 감자전, 해물전, 육전, 배추전, 동태전, 두부전 Pajeon", image: "/images/pajeon.webp" },
    { menu: "전복죽, 호박죽, 단팥죽, 귀리죽, 낙지죽, 소고기죽, 해물죽, 야채죽, 흑임자죽 jeonbok juk, rice porridge", image: "/images/juk.jpg" },
    { menu: "삼계탕 전복삼계탕 녹두삼계탕 닭한마리 Samgyetang, Ginseng Chicken Soup", image: "/images/samgyetang.jpg" },
    { menu: "콩나물국밥 콩나물비빔밥 Kongnamulbap, Bean Sprout Soup ", image: "/images/knm.jpg" },
    { menu: "장어구이 장어덮밥 jangeo gui, Grilled eel", image: "/images/jang-eo-gui.jpg" },
    { menu: "꽃게탕 kkotgetang, Spicy Blue Crab Stew", image: "/images/ggt.jpg" },
    { menu: "잔치국수 Janchiguksu, Banquet Noodles", image: "/images/jcgs.jpg" },
    { menu: "육회 육회비빔밥, Beef Tartare", image: "/images/yookhoe.jpg" },
    { menu: "삼겹살 오겹살 갈매기살 항정살 쭈꾸미삼겹살 콩불 Samgyeopsal, Pork Belly", image: "/images/samgyeopsal.jpg" },
    { menu: "제육볶음 제육쌈밥 제육비빔밥 제육덮밥 jeyukbokkeum, Stir-fried Pork", image: "/images/jeyook.jfif" },
    { menu: "닭갈비 불닭 치즈불닭 치즈닭갈비 Dakgalbi, Spicy Stir-fried Chicken", image: "/images/dgb.jpg" },
    { menu: "닭꼬치 Dak Kkochi, chicken skewers", image: "/images/dkch.jpg" },
    { menu: "돼지껍데기 dwaejikkeopdegi, Stir-fried Pork Rind", image: "/images/djgdg.webp" },
    { menu: "훈제오리, 오리주물럭 hunjeor, smoked duck", image: "/images/hjori.jpg" },
    { menu: "갈비찜 LA갈비찜 Galbijjim, stewed ribs", image: "/images/galbijjim.jpg" },
    { menu: "숯불갈비, 소양념갈비, LA갈비, 등갈비, 매운등갈비 Sutbulgalbi, Charcoal-grilled Galbi", image: "/images/sutbul-galbi.jpg" },
    { menu: "뚝배기 불고기 ttukbaegi bulgogi, hot-pot bulgogi ", image: "/images/ddb.jpg" },
    { menu: "꼬막, 꼬막비빔밥 kkomak bibimbap, cockle bibimbap", image: "/images/kkm.jpg" },
    { menu: "성게알 비빔밥, 멍게 비빔밥 meongge bibimbap, sea pineapple bibimbap", image: "/images/mgbbb.jpg" },
    { menu: "돼지고기 수육 보쌈 dwaeji suyuk, Boiled pork slices", image: "/images/suyook.jpg" },
    { menu: "홍합탕 Honghabtang, mussel soup in a hot pot", image: "/images/honghab.jpg" },
    { menu: "떡국 Tteok-guk, Rice cake soup", image: "/images/tgtg.webp" },
    { menu: "폭탄 계란찜 Steamed Egg", image: "/images/grj.webp" },
    { menu: "곰탕 나주곰탕 꼬리곰탕 Gom-tang", image: "/images/gomtang.webp" },
    { menu: "호떡 Hotteok", image: "/images/hott.webp" },
    { menu: "잡채 Japchae", image: "/images/japchae.webp" },
    { menu: "미역국 Miyeok-guk, Seaweed soup", image: "/images/myg.webp" },
    { menu: "콩국수 Kong-guksu", image: "/images/cgscgs.webp" },
    { menu: "오이 냉국 Cucumber naeng-guk", image: "/images/ngng.webp" },
    { menu: "메밀국수 막국수 춘천막국수 들기름막국수 Memil-guksu", image: "/images/mmgs.webp" },
    { menu: "산낙지 San-nakji, Live Octopus", image: "/images/sannak.webp" },
    { menu: "조개구이 가리비구이 Grilled Clams", image: "/images/jgjgjg.webp" },
    { menu: "고등어구이 삼치구이 생선구이 Grilled Fish, Grilled Mackerel", image: "/images/mackeee.webp" },
    { menu: "감자조림 매운감자조림 알감자조림 Gamja-jorim", image: "/images/gamjajorim.jpg" },
    { menu: "소고기무국 뭇국 무국 Radish soup", image: "/images/moot.webp" },
    { menu: "곱창 소고찹 곱창전골 Gobchang", image: "/images/gobchang.webp" },
    { menu: "두부조림 Dubu-jorim", image: "/images/dbjr.webp" },
    { menu: "간장계란밥 Fried rice with Soy sauce and eggs", image: "/images/gjgr.jpg" },
    { menu: "두루치기 돼지두루치기 Duruchigi", image: "/images/duru.webp" },
    { menu: "알탕 추어탕 Altang", image: "/images/altang.jpg" },
    { menu: "추어탕 Choo-eo-tang", image: "/images/choot.webp" },
    { menu: "닭발 닭똥집 Chicken Feet", image: "/images/dakbb.jpg" },
    { menu: "돼지껍데기 Pork skin", image: "/images/djggg.jpg" },
    { menu: "스테이크 솥밥", image: "/images/sotbap.webp" },
    // added

      { menu: "강릉감자옹심이", image: "/images/converted_강릉감자옹심이.webp" },
      { menu: "강릉초당순두부", image: "/images/converted_강릉초당순두부.webp" },
      { menu: "거제대구탕", image: "/images/converted_거제대구탕.webp" },
      { menu: "거제볼락구이", image: "/images/converted_거제볼락구이.webp" },
      { menu: "고성하모회", image: "/images/converted_고성하모회.webp" },
      { menu: "고창풍천장어구이", image: "/images/converted_고창풍천장어구이.webp" },
      { menu: "광양불고기", image: "/images/converted_광양불고기.webp" },
      { menu: "광주송정떡갈비", image: "/images/converted_광주송정떡갈비.webp" },
      { menu: "광주애호박찌개", image: "/images/converted_광주애호박찌개.webp" },
      { menu: "광주오리탕", image: "/images/converted_광주오리탕.webp" },
      { menu: "괴산올갱이국", image: "/images/converted_괴산올갱이국.webp" },
      { menu: "금산어죽", image: "/images/converted_금산어죽.webp" },
      { menu: "김해뒷고기", image: "/images/converted_김해뒷고기.webp" },
      { menu: "김해진영갈비", image: "/images/converted_김해진영갈비.webp" },
      { menu: "나주곰탕", image: "/images/converted_나주곰탕.webp" },
      { menu: "나주영산포홍어", image: "/images/converted_나주영산포홍어.webp" },
      { menu: "남원추어탕", image: "/images/converted_남원추어탕.webp" },
      { menu: "남해멸치쌈밥", image: "/images/converted_남해멸치쌈밥.webp" },
      { menu: "논산강경젓갈", image: "/images/converted_논산강경젓갈.webp" },
      { menu: "논산위어회", image: "/images/converted_논산위어회.webp" },
      { menu: "담양마늘떡갈비", image: "/images/converted_담양마늘떡갈비.webp" },
      { menu: "담양대통밥", image: "/images/converted_담양대통밥.webp" },
      { menu: "담양돼지갈비", image: "/images/converted_담양돼지갈비.webp" },
      { menu: "담양창평국밥", image: "/images/converted_담양창평국밥.webp" },
      { menu: "당진실치회", image: "/images/converted_당진실치회.webp" },
      { menu: "대구납작만두", image: "/images/converted_대구납작만두.webp" },
      { menu: "대구동인동찜갈비", image: "/images/converted_대구동인동찜갈비.webp" },
      { menu: "대구막창", image: "/images/converted_대구막창.webp" },
      { menu: "대구오드레기", image: "/images/converted_대구오드레기.webp" },
      { menu: "대구중화비빔밥", image: "/images/converted_대구중화비빔밥.webp" },
      { menu: "대구찜갈비", image: "/images/converted_대구찜갈비.webp" },
      { menu: "대전두부두루치기", image: "/images/converted_대전두부두루치기.webp" },
      { menu: "대전방치찜", image: "/images/converted_대전방치찜.webp" },
      { menu: "목포세발낙지", image: "/images/converted_목포세발낙지.webp" },
      { menu: "목포홍어삼합", image: "/images/converted_목포홍어삼합.webp" },
      { menu: "무안짚불구이", image: "/images/converted_무안짚불구이.webp" },
      { menu: "밀양돼지국밥", image: "/images/converted_밀양돼지국밥.webp" },
      { menu: "보령간재미회무침", image: "/images/converted_보령간재미회무침.webp" },
      { menu: "보성녹차떡갈비", image: "/images/converted_보성녹차떡갈비.webp" },
      { menu: "보성벌교꼬막정식", image: "/images/converted_보성벌교꼬막정식.webp" },
      { menu: "보성어탕", image: "/images/converted_보성어탕.webp" },
      { menu: "봉화솔잎꿩불고기", image: "/images/converted_봉화솔잎꿩불고기.webp" },
      { menu: "봉화송이돌솥밥", image: "/images/converted_봉화송이돌솥밥.webp" },
      { menu: "부산돼지국밥", image: "/images/converted_부산돼지국밥.webp" },
      { menu: "부산재첩국", image: "/images/converted_부산재첩국.webp" },
      { menu: "부산밀면", image: "/images/converted_부산밀면.webp" },
      { menu: "부안백합죽", image: "/images/converted_부안백합죽.webp" },
      { menu: "삼척곰치국", image: "/images/converted_삼척곰치국.webp" },
      { menu: "서산어리굴젓", image: "/images/converted_서산어리굴젓.webp" },
      { menu: "속초오징어순대", image: "/images/converted_속초오징어순대.webp" },
      { menu: "순천짱뚱어탕", image: "/images/converted_순천짱뚱어탕.webp" },
      { menu: "신안민어회", image: "/images/converted_신안민어회.webp" },
      { menu: "안동간고등어정식", image: "/images/converted_안동간고등어정식.webp" },
      { menu: "양양섭국", image: "/images/converted_양양섭국.webp" },
    
      // Image 2
      { menu: "충주시래기순대국", image: "/images/converted_충주시래기순대국.webp" },
      { menu: "태백닭칼국수", image: "/images/converted_태백닭칼국수.webp" },
      { menu: "태백물닭갈비", image: "/images/converted_태백물닭갈비.webp" },
      { menu: "태안게국지", image: "/images/converted_태안게국지.webp" },
      { menu: "태안박속낙지탕", image: "/images/converted_태안박속낙지탕.webp" },
      { menu: "통영도다리쑥국", image: "/images/converted_통영도다리쑥국.webp" },
      { menu: "통영멍게비빔밥", image: "/images/converted_통영멍게비빔밥.webp" },
      { menu: "통영충무김밥", image: "/images/converted_통영충무김밥.webp" },
      { menu: "평창메밀전병", image: "/images/converted_평창메밀전병.webp" },
      { menu: "평창송어회", image: "/images/converted_평창송어회.webp" },
      { menu: "포항과메기", image: "/images/converted_포항과메기.webp" },
      { menu: "포항물회", image: "/images/converted_포항물회.webp" },
      { menu: "하동은어밥", image: "/images/converted_하동은어밥.webp" },
      { menu: "하동재첩국", image: "/images/converted_하동재첩국.webp" },
      { menu: "하동참게가리장", image: "/images/converted_하동참게가리장.webp" },
      { menu: "함양안의갈비찜", image: "/images/converted_함양안의갈비찜.webp" },
      { menu: "해남떡갈비", image: "/images/converted_해남떡갈비.webp" },
      { menu: "홍성대하구이", image: "/images/converted_홍성대하구이.webp" },
      { menu: "홍성새조개샤브", image: "/images/converted_홍성새조개샤브.webp" },
      { menu: "화순순두부", image: "/images/converted_화순순두부.webp" },
      { menu: "횡성안흥찐빵", image: "/images/converted_횡성안흥찐빵.webp" }, // '황성'이 아닌 '횡성'으로 추정하여 수정했습니다.
    
      // Image 3
      { menu: "여수금풍생이구이", image: "/images/converted_여수금풍생이구이.webp" },
      { menu: "여수돌게장", image: "/images/converted_여수돌게장.webp" },
      { menu: "여수서대회", image: "/images/converted_여수서대회.webp" },
      { menu: "여수하모유비끼", image: "/images/converted_여수하모유비끼.webp" },
      { menu: "영광법성포굴비정식", image: "/images/converted_영광법성포굴비정식.webp" },
      { menu: "영덕대게찜", image: "/images/converted_영덕대게찜.webp" },
      { menu: "영암갈낙탕", image: "/images/converted_영암갈낙탕.webp" },
      { menu: "영암매생이떡국", image: "/images/converted_영암매생이떡국.webp" },
      { menu: "영월칡국수", image: "/images/converted_영월칡국수.webp" },
      { menu: "영주메밀묵밥", image: "/images/converted_영주메밀묵밥.webp" },
      { menu: "예산갈비", image: "/images/converted_예산갈비.webp" },
      { menu: "예천오징어불고기", image: "/images/converted_예천오징어불고기.webp" },
      { menu: "예천용궁순대", image: "/images/converted_예천용궁순대.webp" },
      { menu: "옥천도리뱅뱅이", image: "/images/converted_옥천도리뱅뱅이.webp" },
      { menu: "옥천어국수", image: "/images/converted_옥천어국수.webp" },
      { menu: "완도전복죽", image: "/images/converted_완도전복죽.webp" },
      { menu: "울산고래고기", image: "/images/converted_울산고래고기.webp" },
      { menu: "울산언양불고기", image: "/images/converted_울산언양불고기.webp" },
      { menu: "울진대게와붉은대게", image: "/images/converted_울진대게와붉은대게.webp" },
      { menu: "원주추어탕", image: "/images/converted_원주추어탕.webp" },
      { menu: "의령망개떡", image: "/images/converted_의령망개떡.webp" },
      { menu: "의령메밀소바", image: "/images/converted_의령메밀소바.webp" },
      { menu: "의령소고기국밥", image: "/images/converted_의령소고기국밥.webp" },
      { menu: "의성마늘통닭", image: "/images/converted_의성마늘통닭.webp" },
      { menu: "익산황등비빔밥", image: "/images/converted_익산황등비빔밥.webp" },
      { menu: "인제황태정식", image: "/images/converted_인제황태정식.webp" },
      { menu: "장흥된장물회", image: "/images/converted_장흥된장물회.webp" },
      { menu: "장흥삼합", image: "/images/converted_장흥삼합.webp" },
      { menu: "전주콩나물국밥", image: "/images/converted_전주콩나물국밥.webp" },
      { menu: "정선곤드레밥", image: "/images/converted_정선곤드레밥.webp" },
      { menu: "정선콧등치기국수", image: "/images/converted_정선콧등치기국수.webp" },
      { menu: "정선황기족발", image: "/images/converted_정선황기족발.webp" },
      { menu: "제천빨간오뎅", image: "/images/converted_제천빨간오뎅.webp" },
      { menu: "진도굴물회", image: "/images/converted_진도굴물회.webp" },
      { menu: "진주냉면", image: "/images/converted_진주냉면.webp" },
      { menu: "진주비빔밥", image: "/images/converted_진주비빔밥.webp" },
      { menu: "창원떡전어", image: "/images/converted_창원떡전어.webp" },
      { menu: "창원미더덕덮밥", image: "/images/converted_창원미더덕덮밥.webp" },
      { menu: "창원아구찜", image: "/images/converted_창원아구찜.webp" },
      { menu: "창원진동오리주물럭", image: "/images/converted_창원진동오리주물럭.webp" },
      { menu: "창원해초비빔밥", image: "/images/converted_창원해초비빔밥.webp" },
      { menu: "청도미나리삼겹살", image: "/images/converted_청도미나리삼겹살.webp" },
      { menu: "청도추어탕", image: "/images/converted_청도추어탕.webp" },
      { menu: "청송닭불고기", image: "/images/converted_청송닭불고기.webp" },
      { menu: "청주짜글이", image: "/images/converted_청주짜글이.webp" },
      { menu: "춘천닭갈비", image: "/images/converted_춘천닭갈비.webp" },
      { menu: "충주막국수", image: "/images/converted_충주막국수.webp" },
      { menu: "충주꿩샤브", image: "/images/converted_충주꿩샤브.webp" },
      { menu: "충주민물새우탕", image: "/images/converted_충주민물새우탕.webp" }

  ],
  pizza: [
    { menu: "피자, 고르곤졸라피자, 콰트로 포르마지 피자, 프로슈토 풍기 피자, 시카고 피자, 디트로이트 피자, Pizza, Quattro Formaggi, Prosciutto e Funghi, Chicago Pizza, Detroit Pizza", image: "/images/pizza.jpg" },
    { menu: "치킨, Chicken", image: "/images/chicken.jpg" },
    { menu: "햄버거, Hamburger", image: "/images/hamburger.jpg" },
    { menu: "팬케이크, Pancake", image: "/images/pancake.jpg" },
    { menu: "와플, Waffle", image: "/images/waffle.jpg" },
    { menu: "샌드위치, Sandwich", image: "/images/sandwich.jpg" },
    { menu: "핫도그, 명랑핫도그, Hot dog, Corn dog", image: "/images/hot-dog.jpg" },
    { menu: "토스트, Toast", image: "/images/toast.jpg" },
    { menu: "치즈스틱, Cheese Stick", image: "/images/cheese-sticks.jpg" },
    { menu: "붕어빵 Boong-eoh Bbang", image: "/images/bb.jpg" },
    { menu: "닭강정 Dak Kang Jung", image: "/images/dakgangjeong.jpg" },
    { menu: "스테이크 Beef Steak", image: "/images/steak.jpg" },
    { menu: "보르시 borscht", image: "/images/borscht.jpg" },
    { menu: "폭립 Pork Rib", image: "/images/porkrib.jpg" },
    { menu: "연어 스테이크 Salmon Steak", image: "/images/salmonsteak.jpg" },
    { menu: "연어 샐러드, 훈제연어 Salmon Salad", image: "/images/salmon.jpeg" },
    { menu: "당근 케이크 Carrot Cake", image: "/images/carrotcake.jpeg" },
    { menu: "오믈렛 Omelette", image: "/images/omelette.jpg" },
    { menu: "햄 치즈 마카로니 Ham Cheese Macaroni", image: "/images/hcm.jpg" },
    { menu: "샤슬릭, Шашлык, Skewers", image: "/images/ssl.webp" },
    { menu: "도넛 Donut", image: "/images/donut.webp" },
    { menu: "프레첼 Pretzel", image: "/images/pretzel.webp" },
    { menu: "뮤즐리 Musli", image: "/images/musli.jpg" },
    { menu: "포케, 연어 포케 Poke", image: "/images/poke.jpg" },
  ],
  mexico: [
    { menu: "타코, Taco", image: "/images/tacos.jpg" },
    { menu: "칠레스 엔 노가다 Chiles en nogada", image: "/images/chiles.jpg" },
    { menu: "엔칠라다 Enchiladas", image: "/images/enchiladas.jpg" },
    { menu: "케사디아, Quesadilla", image: "/images/quesadilla.jpg" },
    { menu: "감바스 알 아히요, Gambas al ajillo", image: "/images/gambas.jpg" },
    { menu: "타말레스 Tamales", image: "/images/tamales.jpg" },
    { menu: "포졸레 Pozole", image: "/images/pozole.jpg" },
    { menu: "코치니타 피빌 Cochinita Pibil", image: "/images/Cochinita-Pibil.jfif" },
    { menu: "몰레 포블라노 Mole Poblano, a thick, rich red or brown sauce made with chilis, fruit, nuts, seeds and Mexican chocolate ", image: "/images/mole-poblano.jpg" },
    { menu: "토스타다스 Tostadas, refers to dishes made over crispy flat tortillas that are either oven toasted or fried", image: "/images/tostadas.webp" },
    { menu: "빠에야 Paella", image: "/images/paella.jpg" },
    { menu: "가스파초 Gazpacho, ", image: "/images/gazpacho.jpg" },
    { menu: "타파스 Tapas", image: "/images/tapas.jpg" },
    { menu: "세비체 Ceviche, fish or shellfish marinated in citrus and seasonings", image: "/images/ceviche.jpg" },
    { menu: "비리아 Birria, a meat stew or soup traditionally made from goat meat, but occasionally made from beef, lamb, mutton or chicken", image: "/images/birria.jpg" },
    { menu: "파히타 Fajitas", image: "/images/fajitas.jpg" },
    { menu: "과카몰리 Guacamole", image: "/images/guacamole.jpg" },
    { menu: "엠파나다, Empanada", image: "/images/epnd.webp" },
    { menu: "꼬싱야, Coxinha", image: "/images/coxinha.jpg" },
  ],
  china: [
    { menu: "짜장면/짬뽕/삼선짜장, Jjajangmyun", image: "/images/jjajangmyun.jpg" },
    { menu: "탕수육, 김치피자탕수육 Tang Su Yook", image: "/images/tangsuyook.jpg" },
    { menu: "마라탕 Mala Tang", image: "/images/malatang.jfif" },
    { menu: "양장피 YangJangPi", image: "/images/yjp.jfif" },
    { menu: "고추잡채 Red Pepper Japchae", image: "/images/gcj.jpg" },
    { menu: "깐풍기 Kkan Pung-gi", image: "/images/kpg.jfif" },
    { menu: "마라샹궈 Mala Xiang gou", image: "/images/mlsg.jpg" },
    { menu: "유산슬 Yoo San-seul", image: "/images/yss.jfif" },
    { menu: "칠리새우 Chili Shrimp", image: "/images/chili-shrimp.jfif" },
    { menu: "딤섬 Dimsum", image: "/images/dim-sum.jpg" },
    { menu: "팔보채 Pal Bo chae", image: "/images/pbc.jpg" },
    { menu: "꿔바로우 guo bao rou", image: "/images/gbr.jpg" },
    { menu: "마파두부 Mafa Tofu", image: "/images/mafatofu.jpg" },
    { menu: "훠궈 사브사브 핫팟 나베 Hotpot", image: "/images/shabu.jpg" },
    { menu: "북경오리 베이징덕 Peking Duck", image: "/images/pekingduck.webp" },
    { menu: "샤오롱바오, Xiaolongbao", image: "/images/xiaolong.webp" },
  ],
  japan: [
    { menu: "라멘 Ramen", image: "/images/ramen.jpg" },
    { menu: "덴뿌라 Tempura", image: "/images/tempura.jpg" },
    { menu: "스시 Sushi", image: "/images/sushi.jpg" },
    { menu: "돈카츠, 경양식 돈까스 Tonkatsu, pork cutlet", image: "/images/tonkatsu.jpg" },
    { menu: "야끼도리 Yakitori, Chicken Skewers", image: "/images/yakitori.webp" },
    { menu: "우동 김치우동 가케우동 가마아게우동 츠케지루우동 Udon", image: "/images/udon.jpg" },
    { menu: "오코노미야키 Okonomiyaki", image: "/images/okonomiyaki.jpg" },
    { menu: "타코야키 Takoyaki", image: "/images/takoyaki.jpg" },
    { menu: "치라시스시 치라시볼 Chirashi Bowl", image: "/images/chirashi.jpg" },
    { menu: "스키야키 Sukiyaki", image: "/images/sukiyaki.webp" },
    { menu: "돈부리 Donburi", image: "/images/donburi.webp" },
    { menu: "소바 Soba Noodles", image: "/images/soba.jpg" },
    { menu: "오야코동 Oyakodon", image: "/images/oyakodon.webp" },
    { menu: "오차즈케 Chazuke, Green Tea Rice", image: "/images/och.webp" },
    { menu: "후토마키 노리마키 Norimaki", image: "/images/htmk.jfif" },
  ],
  asia: [
    { menu: "쌀국수, Pho", image: "/images/pho.jpg" },
    { menu: "분짜 Buncha", image: "/images/bunjja.jpg" },
    { menu: "팟타이 Pad Thai", image: "/images/pod.jpg" },
    { menu: "반미 샌드위치 Banh Mi Vietnamese Sandwich", image: "/images/banhmi.jpg" },
    { menu: "쏨땀 태국 샐러드 Somtam, Thai papaya sald", image: "/images/somtam.jpg" },
    { menu: "망고 찹쌀밥, Mango Sticky Rice", image: "/images/mango.jpg" },
    { menu: "푸팟 퐁 커리 poo paht pong curry", image: "/images/pppcurry.jpg" },
    { menu: "나시 고랭 Nasi goreng", image: "/images/nasi-goreng.jpg" },
    { menu: "라브 가이 태국 샐러드 larb gai", image: "/images/larb-gai.jfif" },
    { menu: "인도 마크니, 빈달루, 코르마, 도피아자, 마사만, 파낭 커리 & 난", image: "/images/indiancurry.jpg" },
    { menu: "탄두리 치킨", image: "/images/tanduri.jpg" },
    { menu: "양꼬치 Lamb Skewers", image: "/images/yangkkochi.jpg" },
    { menu: "똠양꿍 Tom Yum Soup", image: "/images/tygtyg.webp" },
    { menu: "월남쌈 Vietnamese spring rolls", image: "/images/vietssam.webp" }
  ],
  italy: [
    { menu: "라자냐 Lasagna", image: "/images/lasagna.jpg" },
    { menu: "카프레제 Caprese salad", image: "/images/caprese.jpg" },
    { menu: "젤라또 Gelato", image: "/images/gelato.jpg" },
    { menu: "파스타 알리오올리오, 봉골레, 바질페스토, 명란, 까르보나라, 볼로네제, 크림, 로제, 투움바, 아라비아따, 라구 Pasta", image: "/images/pasta.jpg" },
    { menu: "마르게리따 피자 Margherita Pizza", image: "/images/margherita-pizza.jpg" },
    { menu: "리조또 Risotto", image: "/images/risotto.jpg" },
    { menu: "오소부코 Osso Buco", image: "/images/osso-buco.jpg" },
    { menu: "브루스케타 Bruschetta", image: "/images/bruschetta.jpg" },
    { menu: "티라미수 Tiramisu", image: "/images/tiramisu.jpg" },
    { menu: "햄과 멜론 Prosciutto e Melone", image: "/images/prosciutto-e-melone.jpg" },
    { menu: "파니니 Panini", image: "/images/panini.jpg" },
    { menu: "라비올리 Ravioli", image: "/images/lavioli.webp" },
    { menu: "구안찰레 Guanciale", image: "/images/guanciale.webp"},
    { menu: "파스타 에 파졸리 Pasta e fagioli", image: "/iamges/pastafazool.webp"},
    { menu: "토르텔리니 인 브로도, Tortellini Nel Brodo", image: "images/Tortellini.png" }
    //메젤루나, 프리톨라, 추파 잉글레세 Zuppa Inglese, 
    //수골리
    //Loading, 이미지 skeleton
    //setTimeout
  ],
  france: [
    { menu: "크로크무슈 Croque-Monsieur", image: "/images/croque.webp" },
    { menu: "키쉬 로레인 Quiche Lorraine", image: "/images/quiche.jpg" },
    { menu: "니수아즈 샐러드 Salade Niçoise", image: "/images/salade.jpg" },
    { menu: "코코뱅 Coq au Vin, Chicken soup", image: "/images/coqauvin.jfif" },
    { menu: "라따뚜이 Ratatouille", image: "/images/ratatouille.jpg" },
    { menu: "부야베스 해물스튜 Bouillabaisse", image: "/images/bouillabaisse.jpg" },
    { menu: "케넬 드 브로쉐 만두 Quenelles de Brochet", image: "/images/quenelles.jfif" },
    { menu: "스테이크 감자프라이 Steak Frites", image: "/images/steak-frites.jpg" },
    { menu: "물 마리니에 홍합 Moules Marinières", image: "/images/moules.jpg" },
    { menu: "타르트 태탕 사과파이 Tarte Tatin", image: "/images/tarte-tatin.webp" },
    { menu: "부야베스 Bouillabaisse, French Seafood Stew", image: "/images/bouillabaisse.jpg" },
    { menu: "크레페 Crêpe, French Pancake", image: "/images/crepe.jpg" },
    { menu: "크림/치즈/감자 그라탕 Gratin", image: "/images/gratin.jpg" },
    { menu: "에스까르고 Escargot", image: "/images/escargot.jpg" },
    { menu: "포아그라 Foie Gras", image: "/images/foie-Gras.webp" },
    { menu: "크렘 브륄레 Crème Brûlée", image: "/images/creambr.jfif" },
    { menu: "마들렌 Madeleines", image: "/images/madeleines.jpg" },
    { menu: "프랑스 토스트 French Toast", image: "/images/frenchtoast.jpg" },
    { menu: "크로켓 Croquette", image: "/images/crocket.jpg" },
    { menu: "마카롱 Macaron", image: "/images/macaron.jpg" },
    { menu: "양파 수프 Onion Soup", image: "/images/onionsoup.jpg" },
    { menu: "클레멘타인 크럼블 Clémentines en crumble", image: "/images/clementine.jpg" },
    { menu: "말린 과일을 곁들인 호박 벨루테 Velouté de potiron aux fruits secs muscade", image: "/images/veloute.jpeg" },
    { menu: "프랑스식 양갈비 Côte de Boeuf", image: "/images/ygb.jpg" },
    { menu: "스테이크 타르타르 프랑스식 육회, Tartare", image: "/images/sttt.jpg" },
    { menu: "타르트 플람베, tarte flambee", image: "/images/tftftf.jpg" },
    { menu: "크림 카라멜, Crème caramel", image: "/images/cc22.jpg" },
    { menu: "레몬 타르트, 타르트 오 시트롱, Tarte au citron", image: "/images/tartecit.jpg" },
  ]
};

// Populate the 'all' category
Object.values(menus).forEach(countryMenu => {
  menus.all = menus.all.concat(countryMenu);
});